### ISSUE TITLE
[Question] How to compile cwsr_trap_handler_gfx9.asm

### ISSUE THREAD

**Issue by ASCII128514** [ROCm/ROCK-Kernel-Driver#164]
Hello everyone,

I am new to the ROCM driver. As I am working on the cwsr_trap_handler_gfx9.asm trap handler, I found that the compilation uses sp3. However, I'm not sure where to find the sp3 program to compile the cwsr_trap_handler_gfx9.asm. I've also looked at the sp3-to-mc program located in https://github.com/ROCm/LLVM-AMDGPU-Assembler-Extra However, it fails to compile using llvm-mc.

I am wondering if there is a way to get the sp3 program required by cwsr_trap_handler_gfx9.asm

**Comment by kentrussell** [comment]
Unfortunately I am told there is no plan to release sp3 to the public, due to legal reasons.

We are aware that the trap handler in its current form can't be compiled with LLVM, and the KFD team has it on their roadmap to get the trap handler rewritten to work with LLVM, but there is no timeframe for that right now. But it's definitely something we want to get addressed.
